### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by philleer** [openMVG/SfM_quality_evaluation#6]
[link](http://cvlabwww.epfl.ch/data/multiview/) for C. Strecha, W. von Hansen, L. Van Gool, P. Fua, U. Thoennessen "On Benchmarking Camera Calibration and Multi-View Stereo for High Resolution Imagery" CVPR 2008 is invalid now, could you kindly update it?

**Comment by pmoulon** [comment]
The images and the GT are here: https://github.com/openMVG/SfM_quality_evaluation/tree/master/Benchmarking_Camera_Calibration_2008
If you refer to the paper you can see it here http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.329.6115&rep=rep1&type=pdf

**Comment by philleer** [comment]
Okay. Thanks very much!
